/* home pattern: product-preview-first — editable brief and production rail above the fold */
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { useAuthProfileReady, useJobs, useMutations, useQuery } from 'deepspace'
import { Clapperboard, FileText, Image, Mic2, Play, Save, Sparkles } from 'lucide-react'
import { Button, Input, Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Textarea, useToast } from '../../components/ui'
import { SCOPE_ID } from '../../constants'
import { countWords, narrationFitsFiveSeconds, NARRATION_HARD_MAX_WORDS } from '../../lib/narration'
import { DEFAULT_MOTIONBRIEF_VOICE_ID, MOTIONBRIEF_VOICES } from '../../lib/voices'
import { latestStoredAsset, normalizeAssetManifest, upsertAssetManifest, type StoredAsset } from '../../lib/assets'
import { MOTION_GENERATION_BLOCK_REASON, MOTION_GENERATION_ENABLED } from '../../lib/pipeline-config'

type PipelineResult = { projectId:string; pipelineVersion?:number; assetManifest?:unknown[]; brief?:Pick<Project,'title'|'audience'|'objective'|'visualDirection'|'motionDirection'|'narration'|'headline'|'stillPrompt'|'motionPrompt'>; asset?:StoredAsset; temporaryImageUrl?:string; temporaryVideoUrl?:string; temporaryAudioUrl?:string; temporaryRenderUrl?:string; renderCostUsd?:number; storageError?:string }
type Project = { title:string; prompt:string; audience:string; objective:string; visualDirection:string; motionDirection:string; narration:string; voiceId:string; headline:string; stillPrompt:string; motionPrompt:string; pipelineVersion:number; assetManifest:string; imageUrl:string; videoUrl:string; audioUrl:string; renderUrl:string; status:'draft'|'ready'|'rendering'|'complete' }
const seed: Project = { title:'Untitled motion brief', prompt:'', audience:'Curious creators on short-form video', objective:'Make one clear idea feel immediate and worth sharing.', visualDirection:'Editorial still, tactile light, one decisive focal point, portrait-safe composition.', motionDirection:'Slow push-in with restrained environmental movement; no cuts.', narration:'One idea. One frame. Ready to move.', voiceId:DEFAULT_MOTIONBRIEF_VOICE_ID, headline:'MAKE THE IDEA MOVE', stillPrompt:'', motionPrompt:'', pipelineVersion:1, assetManifest:'[]', imageUrl:'', videoUrl:'', audioUrl:'', renderUrl:'', status:'draft' }
const steps = [['Brief',FileText],['Still',Image],['Motion',Play],['Voice',Mic2],['Render',Clapperboard]] as const

function appFileUrl(key:string){return `/api/files/${key.split('/').map(encodeURIComponent).join('/')}?scope=app`}
function storedImageUrl(project:Project){
  const image=latestStoredAsset(project.assetManifest,'image')
  if(image) return appFileUrl(image.key)
  return project.imageUrl
}
function storedVideoUrl(project:Project){
  const video=latestStoredAsset(project.assetManifest,'video')
  if(video) return appFileUrl(video.key)
  return project.videoUrl
}
function storedAudioUrl(project:Project){
  const audio=latestStoredAsset(project.assetManifest,'audio')
  if(audio) return appFileUrl(audio.key)
  return project.audioUrl
}
function storedRenderUrl(project:Project){
  const render=latestStoredAsset(project.assetManifest,'render')
  if(render) return appFileUrl(render.key)
  return project.renderUrl
}
function storedAssetKey(project:Project,kind:StoredAsset['kind']){
  return latestStoredAsset(project.assetManifest,kind)?.key??''
}
function storedAsset(project:Project,kind:StoredAsset['kind']){
  return latestStoredAsset(project.assetManifest,kind)
}
function narrationReservationEstimate(text:string){return text.trim().length*0.000065*1.3}

export default function HomePage() {
  const { isSignedIn } = useAuthProfileReady({ requireUser: true })
  const { records } = useQuery<Project>('motion-projects', { orderBy:'updatedAt', orderDir:'desc', limit:1 })
  const { createConfirmed, putConfirmed, ready } = useMutations<Project>('motion-projects')
  const { enqueue, jobs } = useJobs<unknown, PipelineResult>(SCOPE_ID)
  const toast = useToast()
  const [draft,setDraft] = useState(seed), [recordId,setRecordId] = useState<string|null>(null)
  const [saving,setSaving] = useState(false), [queuing,setQueuing] = useState(false)
  const appliedJob = useRef<string|null>(null)
  const appliedStillJob = useRef<string|null>(null)
  const appliedMotionJob = useRef<string|null>(null)
  const appliedVoiceJob = useRef<string|null>(null)
  const appliedRenderJob = useRef<string|null>(null)
  const loadedRecord = useRef<string|null>(null)
  const stored = records[0], project = draft, previewImageUrl=storedImageUrl(draft), previewVideoUrl=storedVideoUrl(draft), previewAudioUrl=storedAudioUrl(draft), previewRenderUrl=storedRenderUrl(draft)
  const job = useMemo(() => jobs.filter(j => j.type === 'motionbrief-generate-brief' && (!recordId || (j.payload as {projectId?:string}|undefined)?.projectId === recordId)).sort((a,b)=>Date.parse(b.enqueuedAt)-Date.parse(a.enqueuedAt))[0], [jobs,recordId])
  const stillJob = useMemo(() => jobs.filter(j => ['motionbrief-generate-still','motionbrief-store-still'].includes(j.type) && (!recordId || (j.payload as {projectId?:string}|undefined)?.projectId === recordId)).sort((a,b)=>Date.parse(b.enqueuedAt)-Date.parse(a.enqueuedAt))[0], [jobs,recordId])
  const motionJob = useMemo(() => jobs.filter(j => ['motionbrief-generate-motion','motionbrief-store-motion'].includes(j.type) && (!recordId || (j.payload as {projectId?:string}|undefined)?.projectId === recordId)).sort((a,b)=>Date.parse(b.enqueuedAt)-Date.parse(a.enqueuedAt))[0], [jobs,recordId])
  const voiceJob = useMemo(() => jobs.filter(j => ['motionbrief-generate-narration','motionbrief-store-narration'].includes(j.type) && (!recordId || (j.payload as {projectId?:string}|undefined)?.projectId === recordId)).sort((a,b)=>Date.parse(b.enqueuedAt)-Date.parse(a.enqueuedAt))[0], [jobs,recordId])
  const renderJob = useMemo(() => jobs.filter(j => ['motionbrief-render-final','motionbrief-store-render'].includes(j.type) && (!recordId || (j.payload as {projectId?:string}|undefined)?.projectId === recordId)).sort((a,b)=>Date.parse(b.enqueuedAt)-Date.parse(a.enqueuedAt))[0], [jobs,recordId])
  const set = <K extends keyof Project>(key:K,value:Project[K]) => setDraft(current => ({...current,[key]:value}))

  useEffect(()=>{
    if(!stored || loadedRecord.current===stored.recordId) return
    loadedRecord.current=stored.recordId
    setRecordId(stored.recordId)
    setDraft({...seed,...stored.data,assetManifest:normalizeAssetManifest(stored.data.assetManifest??'[]')})
  },[stored])

  async function save() {
    if (!isSignedIn) return toast.info('Sign in to save','The studio preview is open; saving requires an account.')
    const values = {...project,assetManifest:normalizeAssetManifest(project.assetManifest)}
    if (!values.prompt.trim()) return toast.error('Prompt required','Add the creator prompt before saving the brief.')
    if (!narrationFitsFiveSeconds(values.narration)) return toast.error('Narration timing','Use 8–13 words for a five-second read, or leave narration empty.')
    setSaving(true)
    try { if(recordId) await putConfirmed(recordId,{...values,status:'ready'}); else setRecordId(await createConfirmed({...values,status:'ready'})); setDraft({...values,status:'ready'}); toast.success('Brief saved','Your editable production brief is ready.') }
    catch(e){ toast.error('Could not save',e instanceof Error?e.message:'Please try again.') } finally { setSaving(false) }
  }
  async function preview(){ if(!isSignedIn||!recordId) return toast.info('Save first','Sign in and save the brief before previewing.'); setQueuing(true); try{ await enqueue('motionbrief-preview',{projectId:recordId,headline:draft.headline},{maxAttempts:1}); toast.success('Preview queued','Zero-cost orchestration only; no paid integrations called.') }catch(e){toast.error('Could not queue',e instanceof Error?e.message:'Please try again.')}finally{setQueuing(false)} }
  async function generateBrief(){ if(!isSignedIn||!recordId) return toast.info('Save first','Sign in and save your creator prompt first.'); setQueuing(true); try{ await enqueue('motionbrief-generate-brief',{projectId:recordId,prompt:project.prompt},{maxAttempts:1}); toast.success('AI brief queued','This owner-approved action makes one paid OpenAI request.') }catch(e){toast.error('Could not queue',e instanceof Error?e.message:'Please try again.')}finally{setQueuing(false)} }
  async function generateStill(){ if(!isSignedIn||!recordId) return toast.info('Save first','Save the AI brief before generating a still.'); const recover=stillJob?.result?.temporaryImageUrl; if(!recover&&!project.stillPrompt.trim()) return toast.error('Still prompt missing','Generate or enter a still prompt first.'); setQueuing(true); try{ if(recover){await enqueue('motionbrief-store-still',{projectId:recordId,sourceUrl:recover},{maxAttempts:1}); toast.success('Storage retry queued','Reusing the existing FAL image; no generation charge.')}else{await enqueue('motionbrief-generate-still',{projectId:recordId,stillPrompt:project.stillPrompt},{maxAttempts:1}); toast.success('Still queued','One FAL image costs $0.035 with a hard $0.04 ceiling.')} }catch(e){toast.error('Could not queue',e instanceof Error?e.message:'Please try again.')}finally{setQueuing(false)} }
  async function generateMotion(){ if(!isSignedIn||!recordId) return toast.info('Save first','Save the brief before generating motion.'); const recover=motionJob?.result?.temporaryVideoUrl; if(!recover&&!MOTION_GENERATION_ENABLED) return toast.info('Motion temporarily paused',MOTION_GENERATION_BLOCK_REASON); const image=storedAsset(project,'image'); if(!recover&&!image?.sourceUrl) return toast.error('Stored still required','Generate and store a still before animation.'); if(!recover&&!project.motionPrompt.trim()) return toast.error('Motion prompt missing','Generate or enter a motion prompt first.'); setQueuing(true); try{ if(recover){await enqueue('motionbrief-store-motion',{projectId:recordId,sourceUrl:recover},{maxAttempts:1}); toast.success('Video storage retry queued','Reusing the existing FAL video; no generation charge.')}else{await enqueue('motionbrief-generate-motion',{projectId:recordId,motionPrompt:project.motionPrompt,imageUrl:image?.sourceUrl},{maxAttempts:1}); toast.success('Motion queued','Wan generates one silent five-second video with a $0.25 provider cap; estimated DeepSpace reservation is $0.325.')} }catch(e){toast.error('Could not queue',e instanceof Error?e.message:'Please try again.')}finally{setQueuing(false)} }
  async function generateNarration(){ if(!isSignedIn||!recordId) return toast.info('Save first','Save the brief before generating narration.'); const recover=voiceJob?.result?.temporaryAudioUrl; if(!recover&&!narrationFitsFiveSeconds(project.narration)) return toast.error('Narration timing','Use 8–13 words for a five-second read.'); if(!recover&&!project.narration.trim()) return toast.error('Narration required','Enter narration, or leave this phase silent.'); setQueuing(true); try{ if(recover){await enqueue('motionbrief-store-narration',{projectId:recordId,dataUrl:recover},{maxAttempts:1}); toast.success('Audio storage retry queued','Reusing the existing ElevenLabs audio; no generation charge.')}else{await enqueue('motionbrief-generate-narration',{projectId:recordId,narration:project.narration,voiceId:project.voiceId},{maxAttempts:1}); toast.success('Narration queued',`ElevenLabs is billed per character; estimated reservation $${narrationReservationEstimate(project.narration).toFixed(4)}.`)} }catch(e){toast.error('Could not queue',e instanceof Error?e.message:'Please try again.')}finally{setQueuing(false)} }
  async function renderFinal(){ if(!isSignedIn||!recordId) return toast.info('Save first','Save the brief before rendering.'); const recover=renderJob?.result?.temporaryRenderUrl; const video=storedAsset(project,'video'), audio=storedAsset(project,'audio'); if(!recover&&!video) return toast.error('Motion required','A stored motion clip is required before final rendering.'); if(!recover&&project.narration.trim()&&!audio) return toast.error('Narration audio required','Generate narration first, or clear the narration field for a silent render.'); if(!recover&&!project.headline.trim()) return toast.error('Headline required','Enter the one headline before rendering.'); setQueuing(true); try{ if(recover){await enqueue('motionbrief-store-render',{projectId:recordId,sourceUrl:recover},{maxAttempts:1}); toast.success('Final storage retry queued','Reusing the existing Shotstack render; no render charge.')}else{await enqueue('motionbrief-render-final',{projectId:recordId,headline:project.headline,videoKey:video?.key,audioKey:audio?.key},{maxAttempts:1}); toast.success('Final render queued','Shotstack is usage-based and billed per rendered second. This timeline is five seconds.')} }catch(e){toast.error('Could not queue',e instanceof Error?e.message:'Please try again.')}finally{setQueuing(false)} }

  useEffect(()=>{ if(job?.status!=='succeeded'||!job.result?.brief||appliedJob.current===job.id) return; appliedJob.current=job.id; const next={...draft,...job.result.brief,pipelineVersion:job.result.pipelineVersion??1,assetManifest:JSON.stringify(job.result.assetManifest??[]),status:'ready' as const}; setDraft(next); if(recordId) void putConfirmed(recordId,next).then(()=>toast.success('AI brief ready','Review and edit every field before generating assets.')).catch(e=>toast.error('Brief generated but not saved',e instanceof Error?e.message:'Save it manually.')) },[job,draft,putConfirmed,recordId,toast])
  useEffect(()=>{ if(stillJob?.status!=='succeeded'||!stillJob.result?.asset||appliedStillJob.current===stillJob.id) return; appliedStillJob.current=stillJob.id; const next={...draft,imageUrl:appFileUrl(stillJob.result.asset.key),assetManifest:upsertAssetManifest(draft.assetManifest,stillJob.result.asset)}; setDraft(next); if(recordId) void putConfirmed(recordId,next).then(()=>toast.success('Still image ready','The FAL result is copied into durable app storage.')).catch(e=>toast.error('Image ready but not saved',e instanceof Error?e.message:'Save it manually.')) },[stillJob,draft,putConfirmed,recordId,toast])
  useEffect(()=>{ if(stillJob?.status!=='succeeded'||!stillJob.result?.temporaryImageUrl||appliedStillJob.current===stillJob.id) return; appliedStillJob.current=stillJob.id; setDraft(current=>({...current,imageUrl:stillJob.result?.temporaryImageUrl??''})); toast.error('Image generated; storage retry available',stillJob.result.storageError??'Storage failed') },[stillJob,toast])
  useEffect(()=>{ if(motionJob?.status!=='succeeded'||motionJob.result?.asset?.kind!=='video'||appliedMotionJob.current===motionJob.id) return; appliedMotionJob.current=motionJob.id; const next={...draft,videoUrl:appFileUrl(motionJob.result.asset.key),assetManifest:upsertAssetManifest(draft.assetManifest,motionJob.result.asset)}; setDraft(next); if(recordId) void putConfirmed(recordId,next).then(()=>toast.success('Motion ready','The five-second video is in durable app storage.')).catch(e=>toast.error('Video ready but not saved',e instanceof Error?e.message:'Save it manually.')) },[motionJob,draft,putConfirmed,recordId,toast])
  useEffect(()=>{ if(motionJob?.status!=='succeeded'||!motionJob.result?.temporaryVideoUrl||appliedMotionJob.current===motionJob.id) return; appliedMotionJob.current=motionJob.id; setDraft(current=>({...current,videoUrl:motionJob.result?.temporaryVideoUrl??''})); toast.error('Video generated; storage retry available',motionJob.result.storageError??'Storage failed') },[motionJob,toast])
  useEffect(()=>{ if(voiceJob?.status!=='succeeded'||voiceJob.result?.asset?.kind!=='audio'||appliedVoiceJob.current===voiceJob.id) return; appliedVoiceJob.current=voiceJob.id; const next={...draft,audioUrl:appFileUrl(voiceJob.result.asset.key),assetManifest:upsertAssetManifest(draft.assetManifest,voiceJob.result.asset)}; setDraft(next); if(recordId) void putConfirmed(recordId,next).then(()=>toast.success('Narration ready','The ElevenLabs MP3 is in durable app storage.')).catch(e=>toast.error('Narration ready but not saved',e instanceof Error?e.message:'Save it manually.')) },[voiceJob,draft,putConfirmed,recordId,toast])
  useEffect(()=>{ if(voiceJob?.status!=='succeeded'||!voiceJob.result?.temporaryAudioUrl||appliedVoiceJob.current===voiceJob.id) return; appliedVoiceJob.current=voiceJob.id; setDraft(current=>({...current,audioUrl:voiceJob.result?.temporaryAudioUrl??''})); toast.error('Narration generated; storage retry available',voiceJob.result.storageError??'Storage failed') },[voiceJob,toast])
  useEffect(()=>{ if(renderJob?.status!=='succeeded'||renderJob.result?.asset?.kind!=='render'||appliedRenderJob.current===renderJob.id) return; appliedRenderJob.current=renderJob.id; const next={...draft,renderUrl:appFileUrl(renderJob.result.asset.key),assetManifest:upsertAssetManifest(draft.assetManifest,renderJob.result.asset),status:'complete' as const}; setDraft(next); if(recordId) void putConfirmed(recordId,next).then(()=>toast.success('Final MP4 ready',`Stored permanently${typeof renderJob.result?.renderCostUsd==='number'?` · render cost $${renderJob.result.renderCostUsd.toFixed(4)}`:''}.`)).catch(e=>toast.error('Final video ready but not saved',e instanceof Error?e.message:'Save it manually.')) },[renderJob,draft,putConfirmed,recordId,toast])
  useEffect(()=>{ if(renderJob?.status!=='succeeded'||!renderJob.result?.temporaryRenderUrl||appliedRenderJob.current===renderJob.id) return; appliedRenderJob.current=renderJob.id; setDraft(current=>({...current,renderUrl:renderJob.result?.temporaryRenderUrl??''})); toast.error('Render complete; storage retry available',renderJob.result.storageError??'Storage failed') },[renderJob,toast])

  return <div className="min-h-full bg-background text-foreground"><div className="mx-auto grid max-w-[1500px] lg:grid-cols-[minmax(0,1fr)_390px]">
    <section className="min-w-0 border-border lg:border-r"><header className="border-b border-border px-5 py-7 md:px-9"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.22em] text-primary">Prompt to motion</p><h1 className="text-3xl font-semibold tracking-[-.04em] md:text-5xl">Build the brief. Ship the frame.</h1><p className="mt-3 text-muted-foreground">One surface for the idea, image, motion, voice, and vertical cut.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={save} loading={saving} disabled={!ready}><Save/>Save brief</Button><Button variant="outline" onClick={preview} loading={queuing}><Sparkles/>Preview pipeline</Button><Button onClick={generateStill} loading={stillJob?.status==='queued'||stillJob?.status==='running'} disabled={!recordId||(!project.stillPrompt.trim()&&!stillJob?.result?.temporaryImageUrl)}><Image/>{stillJob?.result?.temporaryImageUrl?'Retry storage · $0':'Generate still · $0.035'}</Button><Button onClick={generateMotion} loading={motionJob?.status==='queued'||motionJob?.status==='running'} disabled={!recordId||(!motionJob?.result?.temporaryVideoUrl&&!MOTION_GENERATION_ENABLED)||(!storedAssetKey(project,'image')&&!motionJob?.result?.temporaryVideoUrl)}><Play/>{motionJob?.result?.temporaryVideoUrl?'Retry video storage · $0':MOTION_GENERATION_ENABLED?'Animate · est. $0.325':'Motion paused'}</Button><Button onClick={generateNarration} loading={voiceJob?.status==='queued'||voiceJob?.status==='running'} disabled={!recordId||(!project.narration.trim()&&!voiceJob?.result?.temporaryAudioUrl)}><Mic2/>{voiceJob?.result?.temporaryAudioUrl?'Retry audio storage · $0':`Narrate · est. $${narrationReservationEstimate(project.narration).toFixed(4)}`}</Button><Button onClick={renderFinal} loading={renderJob?.status==='queued'||renderJob?.status==='running'} disabled={!recordId||(!storedAssetKey(project,'video')&&!renderJob?.result?.temporaryRenderUrl)}><Clapperboard/>{renderJob?.result?.temporaryRenderUrl?'Retry final storage · $0':'Render final · usage-based'}</Button></div></div>{!MOTION_GENERATION_ENABLED&&<p className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-sm text-amber-200">Motion paused · Waiting on DeepSpace. No new FAL video attempts will be submitted.</p>}</header>
      <div className="grid gap-8 p-5 md:p-9 xl:grid-cols-[1fr_.72fr]"><div className="space-y-6"><Field label="Creator prompt"><Textarea value={project.prompt} onChange={e=>set('prompt',e.target.value)} placeholder="A launch film for a tiny camera that makes everyday walks feel cinematic…" className="min-h-36 bg-card text-lg leading-relaxed"/>{!project.prompt&&<p className="text-xs text-muted-foreground">Start with the raw thought. Every field remains editable.</p>}<Button className="mt-3" onClick={generateBrief} loading={queuing} disabled={!recordId}><Sparkles/>Generate AI brief</Button></Field><div className="grid gap-5 md:grid-cols-2"><Field label="Project name"><Input value={project.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="Audience"><Input value={project.audience} onChange={e=>set('audience',e.target.value)}/></Field></div><Field label="Objective"><Textarea value={project.objective} onChange={e=>set('objective',e.target.value)} className="min-h-24 bg-card"/></Field><Field label="Visual direction"><Textarea value={project.visualDirection} onChange={e=>set('visualDirection',e.target.value)} className="min-h-24 bg-card"/></Field><Field label="Motion direction"><Textarea value={project.motionDirection} onChange={e=>set('motionDirection',e.target.value)} className="min-h-24 bg-card"/></Field><div className="grid gap-5 md:grid-cols-2"><Field label="Narration"><Textarea value={project.narration} onChange={e=>set('narration',e.target.value)} className="min-h-28 bg-card"/><p className={`text-xs ${countWords(project.narration)>NARRATION_HARD_MAX_WORDS?'text-destructive':'text-muted-foreground'}`}>{countWords(project.narration)} / {NARRATION_HARD_MAX_WORDS} words · target 8–11 · blank means silent</p><Select value={project.voiceId} onValueChange={value=>set('voiceId',value)}><SelectTrigger><SelectValue placeholder="Choose a voice"/></SelectTrigger><SelectContent>{MOTIONBRIEF_VOICES.map(voice=><SelectItem key={voice.id} value={voice.id}>{voice.name} · {voice.style}</SelectItem>)}</SelectContent></Select></Field><Field label="Headline"><Textarea value={project.headline} onChange={e=>set('headline',e.target.value)} className="min-h-28 bg-card font-semibold uppercase"/></Field></div></div>
        <aside><div className="sticky top-6 overflow-hidden rounded-2xl border border-border bg-card shadow-[0_18px_70px_rgba(0,0,0,.28)]"><div className="relative aspect-[9/16] overflow-hidden bg-[#25221b]">{previewRenderUrl?<video src={previewRenderUrl} className="absolute inset-0 h-full w-full object-cover" controls playsInline loop/>:previewVideoUrl?<video src={previewVideoUrl} className="absolute inset-0 h-full w-full object-cover" controls playsInline loop/>:previewImageUrl?<img src={previewImageUrl} alt="Generated MotionBrief still" className="absolute inset-0 h-full w-full object-cover"/>:<><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_24%,rgba(255,107,53,.5),transparent_28%),linear-gradient(145deg,#40372a_0%,#151511_58%,#080807_100%)]"/><div className="absolute left-[12%] top-[18%] h-[38%] w-[70%] rotate-[-8deg] border border-white/20 bg-white/5 backdrop-blur-sm"/></>}{!previewRenderUrl&&<div className="pointer-events-none absolute inset-x-7 bottom-16"><p className="text-[10px] uppercase tracking-[.28em] text-white/55">MotionBrief preview</p><p className="mt-3 text-4xl font-black uppercase leading-[.88] tracking-[-.055em] text-white">{project.headline||'Your headline'}</p></div>}</div>{previewAudioUrl&&!previewRenderUrl&&<div className="border-t border-border p-3"><audio src={previewAudioUrl} controls className="w-full"/></div>}<div className="flex justify-between border-t border-border p-4 text-xs text-muted-foreground"><span>9:16 · 5 seconds</span><span>{previewRenderUrl?'Final MP4':previewAudioUrl?'Stored narration':previewVideoUrl?'Stored motion':previewImageUrl?'Stored still':'Mock · $0.00'}</span></div></div></aside></div></section>
    <aside className="bg-shell p-5 md:p-7"><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">Production rail</p><div className="mt-5 space-y-2">{steps.map(([label,Icon],i)=>{const current=i===0?job:i===1?stillJob:i===2?motionJob:i===3?voiceJob:i===4?renderJob:undefined,active=current&&['queued','running'].includes(current.status),done=i===0?job?.status==='succeeded'||project.status!=='draft':i===1?Boolean(previewImageUrl):i===2?Boolean(previewVideoUrl):i===3?Boolean(previewAudioUrl):i===4?Boolean(previewRenderUrl):false;return <div key={label} className="flex items-center gap-3 rounded-xl border border-border bg-card p-3.5"><div className={`flex h-9 w-9 items-center justify-center rounded-lg ${done?'bg-primary text-primary-foreground':'bg-secondary text-muted-foreground'}`}><Icon/></div><div className="flex-1"><p className="font-medium">{label}</p><p className="text-xs text-muted-foreground">{i===2&&!MOTION_GENERATION_ENABLED&&!done?'Waiting on DeepSpace':current?.status==='failed'?current.error??'Failed':done?'Ready':active?current.progressMessage??'Working':i===0?'Editing':'Waiting'}</p></div><span className="text-xs text-muted-foreground">0{i+1}</span></div>})}</div><div className="mt-6 rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground"><p className="font-medium text-foreground">Final rendering wired</p><p className="mt-1 leading-relaxed">Shotstack combines the stored five-second motion, optional narration, and one headline into a durable 9:16 MP4. Motion remains blocked pending the FAL integration fix.</p></div></aside>
  </div></div>
}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
